'on':
  push:
    branches:
    - main
jobs:
  Development:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Copy to S3
      run: 'aws s3 cp etl/* s3://testproject123bucket/test_demo/'
