'on':
  push:
    branches:
    - main
jobs:
  Development:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Copy to S3
      run: 'sudo aws s3 cp etl/test123.py s3://testags123bucket/test_demo/ '
