'on':
  push:
    branches:
    - main
jobs:
  Production:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Copy to S3
      run: sudo aws s3 cp etl/valur.py https://pharcomm-demo.s3.us-west-2.amazonaws.com/laad_test/
        --recursive
