'on':
  push:
    branches:
    - main
jobs:
  Production:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Copy to S3
      run: sudo aws s3 cp etl/pharcomm360demo.py s3://pharcomm-demo/laad_test/ --recursive
