'on':
  push:
    branches:
    - main
jobs:
  Production:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Copy to S3
      run: sudo aws s3 cp etl/ s3://pharcomm360demobucket12/input_file/ --recursive
