name: Deploy Workflow
'on':
  push:
    branches:
    - main
jobs:
  deploy_qa:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Copy to S3
      run: aws s3 cp https://github.com/Srivatsava17/CICD.git/etl s3://codecommitdeploy/github_connection/
        --region us-west-2 --access-key ASIAXWDKBRAVQC2WT76T --secret-key UsTfxVNGpKH6sU102k2QwLwuH+mF3ZlVAGFpqbqQ
    environment:
      name: qa
  deploy_dev:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Copy to S3
      run: aws s3 cp https://github.com/Srivatsava17/CICD.git/etl s3://codecommitdeploy/github_connection/
        --region us-west-2 --access-key ASIAXWDKBRAVQC2WT76T --secret-key UsTfxVNGpKH6sU102k2QwLwuH+mF3ZlVAGFpqbqQ
    environment:
      name: dev
  deploy_prod:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Copy to S3
      run: aws s3 cp https://github.com/Srivatsava17/CICD.git/etl s3://codecommitdeploy/github_connection/
        --region us-west-2 --access-key ASIAXWDKBRAVQC2WT76T --secret-key UsTfxVNGpKH6sU102k2QwLwuH+mF3ZlVAGFpqbqQ
    environment:
      name: prod
