jobs:
  dev:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Deploy to S3
      run: scp -i s3://testingnew1234/demo/ /home/ec2-user /home/ec2-user/example.py
    - name: Copy to S3
      run: aws s3 cp etl/example.py /home/ec2-user/example.py
  qa:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Deploy to S3
      run: scp -i s3://testingnew1234/demo/ /home/ec2-user /home/ec2-user/example.py
    - name: Copy to S3
      run: aws s3 cp etl/example.py /home/ec2-user/example.py
