name: Deploy Workflow
'on':
  push:
    branches:
    - main
jobs:
  deploy_qa:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Deploy to Databricks
      run: scp -i https://github.com/Srivatsava17/CI-CD/tree/main/etl https://github.com/Srivatsava17/CI-CD.git
        dapic2fa308f2a267e7719481ac7d4b1281a@https://agilisium.cloud.databricks.com:dbfs/FileStore/
    - name: Copy to S3
      run: databricks fs cp dbfs/FileStore/ https://s3.console.aws.amazon.com/s3/buckets/codecommitdeploy?region=us-west-2&tab=objects
    environment:
      name: qa
  deploy_dev:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Deploy to Databricks
      run: scp -i https://github.com/Srivatsava17/CI-CD/tree/main/etl https://github.com/Srivatsava17/CI-CD.git
        dapic2fa308f2a267e7719481ac7d4b1281a@https://agilisium.cloud.databricks.com:dbfs/FileStore/
    - name: Copy to S3
      run: databricks fs cp dbfs/FileStore/ https://s3.console.aws.amazon.com/s3/buckets/codecommitdeploy?region=us-west-2&tab=objects
    environment:
      name: dev
  deploy_prod:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Deploy to Databricks
      run: scp -i https://github.com/Srivatsava17/CI-CD/tree/main/etl https://github.com/Srivatsava17/CI-CD.git
        dapic2fa308f2a267e7719481ac7d4b1281a@https://agilisium.cloud.databricks.com:dbfs/FileStore/
    - name: Copy to S3
      run: databricks fs cp dbfs/FileStore/ https://s3.console.aws.amazon.com/s3/buckets/codecommitdeploy?region=us-west-2&tab=objects
    environment:
      name: prod
