name: Deploy Workflow
'on':
  push:
    branches:
    - main
jobs:
  deploy_qa:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Copy to S3
      run: aws s3 sync https://github.com/Srivatsava17/CI-CD.git https://s3.console.aws.amazon.com/s3/buckets/codecommitdeploy?region=us-west-2&tab=objects
    environment:
      name: qa
  deploy_dev:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Copy to S3
      run: aws s3 sync https://github.com/Srivatsava17/CI-CD.git https://s3.console.aws.amazon.com/s3/buckets/codecommitdeploy?region=us-west-2&tab=objects
    environment:
      name: dev
  deploy_prod:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Copy to S3
      run: aws s3 sync https://github.com/Srivatsava17/CI-CD.git https://s3.console.aws.amazon.com/s3/buckets/codecommitdeploy?region=us-west-2&tab=objects
    environment:
      name: prod
