name: Deploy Workflow
'on':
  push:
    branches:
    - main
jobs:
  deploy_qa:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Copy to S3
      run: aws s3 cp --recursive https://github.com/Srivatsava17/CICD.git/etl s3://codecommitdeploy/github_connection/
        --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers
    environment:
      name: qa
  deploy_dev:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Copy to S3
      run: aws s3 cp --recursive https://github.com/Srivatsava17/CICD.git/etl s3://codecommitdeploy/github_connection/
        --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers
    environment:
      name: dev
  deploy_prod:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Copy to S3
      run: aws s3 cp --recursive https://github.com/Srivatsava17/CICD.git/etl s3://codecommitdeploy/github_connection/
        --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers
    environment:
      name: prod
