name: Deploy Workflow
'on':
  push:
    branches:
    - main
jobs:
  deploy_qa:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Copy to EC2
      run: cp etl/example.py /home/ec2-user
    environment:
      name: qa
  deploy_dev:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Copy to EC2
      run: cp etl/example.py /home/ec2-user
    environment:
      name: dev
  deploy_prod:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Copy to EC2
      run: cp etl/example.py /home/ec2-user
    environment:
      name: prod
