stages: dev
qa:
  stage: qa
  script:
  - echo "Running tests"
  - git clone dev
  - git pull
  - scp -i https://s3.console.aws.amazon.com/s3/buckets/codecommitdeploy?region=us-west-2&tab=objects
    dapic2fa308f2a267e7719481ac7d4b1281a@https://github.com/Srivatsava17/CI-CD.git:https://agilisium.cloud.databricks.com
  - databricks fs cp /path/to/databricks/file dbfs/FileStore
  - git add .
  - git commit -m 'Update from S3'
  tags:
  - main
  - TEST-ETL
  environment:
    name: dev
dev:
  stage: dev
  script:
  - echo "Running tests"
  - git clone dev
  - git pull
  - scp -i https://s3.console.aws.amazon.com/s3/buckets/codecommitdeploy?region=us-west-2&tab=objects
    dapic2fa308f2a267e7719481ac7d4b1281a@https://github.com/Srivatsava17/CI-CD.git:https://agilisium.cloud.databricks.com
  - databricks fs cp /path/to/databricks/file dbfs/FileStore
  - git add .
  - git commit -m 'Update from S3'
  tags:
  - main
  - TEST-ETL
  only:
  - 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
  environment:
    name: dev
prod:
  stage: prod
  script:
  - echo "Running tests"
  - git clone dev
  - git pull
  - scp -i https://s3.console.aws.amazon.com/s3/buckets/codecommitdeploy?region=us-west-2&tab=objects
    dapic2fa308f2a267e7719481ac7d4b1281a@https://github.com/Srivatsava17/CI-CD.git:https://agilisium.cloud.databricks.com
  - databricks fs cp /path/to/databricks/file dbfs/FileStore
  - git add .
  - git commit -m 'Update from S3'
  tags:
  - main
  - TEST-ETL
  only:
  - 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
  dependencies:
  - qa
  - dev
  environment:
    name: dev
